### ISSUE TITLE
(async) All button removes existing previously selected items

### ISSUE THREAD

**Issue by jtrussell** [iVantage/angular-ivh-multi-select#9]

**Comment by evsheffield** [comment]
Verified with a failing test case. I'm happy to take a look at this one if you weren't already going to.

**Comment by jtrussell** [comment]
Already got a test and working on it ;)

**Comment by evsheffield** [comment]
Ah, cool beans.

**Comment by jtrussell** [comment]
Too bad I can't spell async...

**Comment by jtrussell** [comment]
@evsheffield Since you're already familiar with the issue would you mind doing a quick review of the test/fix?

**Comment by evsheffield** [comment]
@jtrussell Looks good!
